version: '3'

services:

  db:
    image: postgres:14.12-alpine3.20
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    container_name: shop-db
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data